-- ============================================================================
-- Module: Migration version baseline marker.
--
-- Schema definitions for users, roles, menus, dicts, logs, and relation tables
-- were intentionally moved into dedicated feature migrations:
-- 0004_system_user.sql, 0005_system_role.sql, 0006_system_menu.sql,
-- 0007_system_dict.sql, 0008_system_log.sql, 0009_system_relation.sql.
-- This keeps the historical version chain intact while avoiding duplicate DDL.
-- ============================================================================
