-- ============================================================================
-- Module: Compatibility anchor for workspace-seeded bootstrap.
--
-- Seed data now lives in:
-- 0011_system_seed.sql
-- ============================================================================
