/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MonitoringRouteImport } from './routes/monitoring'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as R404RouteImport } from './routes/404'
import { Route as R403RouteImport } from './routes/403'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SystemUserRouteImport } from './routes/system/user'
import { Route as SystemStatusRouteImport } from './routes/system/status'
import { Route as SystemRoleRouteImport } from './routes/system/role'
import { Route as SystemModuleRouteImport } from './routes/system/module'
import { Route as SystemMenuRouteImport } from './routes/system/menu'
import { Route as ReportsTemplatesRouteImport } from './routes/reports/templates'
import { Route as ReportsRunsRouteImport } from './routes/reports/runs'
import { Route as MonitoringOverviewRouteImport } from './routes/monitoring/overview'
import { Route as MonitoringNodesRouteImport } from './routes/monitoring/nodes'
import { Route as MonitoringChecksRouteImport } from './routes/monitoring/checks'
import { Route as ManageTaskRouteImport } from './routes/manage/task'
import { Route as ManageLogRouteImport } from './routes/manage/log'
import { Route as ManageDictRouteImport } from './routes/manage/dict'
import { Route as ManageDeployRouteImport } from './routes/manage/deploy'
import { Route as AnalyticsOverviewRouteImport } from './routes/analytics/overview'
import { Route as AnalyticsDetailsRouteImport } from './routes/analytics/details'

const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemUserRoute = SystemUserRouteImport.update({
  id: '/system/user',
  path: '/system/user',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemStatusRoute = SystemStatusRouteImport.update({
  id: '/system/status',
  path: '/system/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoleRoute = SystemRoleRouteImport.update({
  id: '/system/role',
  path: '/system/role',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemModuleRoute = SystemModuleRouteImport.update({
  id: '/system/module',
  path: '/system/module',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemMenuRoute = SystemMenuRouteImport.update({
  id: '/system/menu',
  path: '/system/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsTemplatesRoute = ReportsTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsRunsRoute = ReportsRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => ReportsRoute,
} as any)
const MonitoringOverviewRoute = MonitoringOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => MonitoringRoute,
} as any)
const MonitoringNodesRoute = MonitoringNodesRouteImport.update({
  id: '/nodes',
  path: '/nodes',
  getParentRoute: () => MonitoringRoute,
} as any)
const MonitoringChecksRoute = MonitoringChecksRouteImport.update({
  id: '/checks',
  path: '/checks',
  getParentRoute: () => MonitoringRoute,
} as any)
const ManageTaskRoute = ManageTaskRouteImport.update({
  id: '/manage/task',
  path: '/manage/task',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageLogRoute = ManageLogRouteImport.update({
  id: '/manage/log',
  path: '/manage/log',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageDictRoute = ManageDictRouteImport.update({
  id: '/manage/dict',
  path: '/manage/dict',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageDeployRoute = ManageDeployRouteImport.update({
  id: '/manage/deploy',
  path: '/manage/deploy',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsOverviewRoute = AnalyticsOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsDetailsRoute = AnalyticsDetailsRouteImport.update({
  id: '/details',
  path: '/details',
  getParentRoute: () => AnalyticsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/404': typeof R404Route
  '/analytics': typeof AnalyticsRouteWithChildren
  '/login': typeof LoginRoute
  '/monitoring': typeof MonitoringRouteWithChildren
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRouteWithChildren
  '/analytics/details': typeof AnalyticsDetailsRoute
  '/analytics/overview': typeof AnalyticsOverviewRoute
  '/manage/deploy': typeof ManageDeployRoute
  '/manage/dict': typeof ManageDictRoute
  '/manage/log': typeof ManageLogRoute
  '/manage/task': typeof ManageTaskRoute
  '/monitoring/checks': typeof MonitoringChecksRoute
  '/monitoring/nodes': typeof MonitoringNodesRoute
  '/monitoring/overview': typeof MonitoringOverviewRoute
  '/reports/runs': typeof ReportsRunsRoute
  '/reports/templates': typeof ReportsTemplatesRoute
  '/system/menu': typeof SystemMenuRoute
  '/system/module': typeof SystemModuleRoute
  '/system/role': typeof SystemRoleRoute
  '/system/status': typeof SystemStatusRoute
  '/system/user': typeof SystemUserRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/404': typeof R404Route
  '/analytics': typeof AnalyticsRouteWithChildren
  '/login': typeof LoginRoute
  '/monitoring': typeof MonitoringRouteWithChildren
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRouteWithChildren
  '/analytics/details': typeof AnalyticsDetailsRoute
  '/analytics/overview': typeof AnalyticsOverviewRoute
  '/manage/deploy': typeof ManageDeployRoute
  '/manage/dict': typeof ManageDictRoute
  '/manage/log': typeof ManageLogRoute
  '/manage/task': typeof ManageTaskRoute
  '/monitoring/checks': typeof MonitoringChecksRoute
  '/monitoring/nodes': typeof MonitoringNodesRoute
  '/monitoring/overview': typeof MonitoringOverviewRoute
  '/reports/runs': typeof ReportsRunsRoute
  '/reports/templates': typeof ReportsTemplatesRoute
  '/system/menu': typeof SystemMenuRoute
  '/system/module': typeof SystemModuleRoute
  '/system/role': typeof SystemRoleRoute
  '/system/status': typeof SystemStatusRoute
  '/system/user': typeof SystemUserRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/404': typeof R404Route
  '/analytics': typeof AnalyticsRouteWithChildren
  '/login': typeof LoginRoute
  '/monitoring': typeof MonitoringRouteWithChildren
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRouteWithChildren
  '/analytics/details': typeof AnalyticsDetailsRoute
  '/analytics/overview': typeof AnalyticsOverviewRoute
  '/manage/deploy': typeof ManageDeployRoute
  '/manage/dict': typeof ManageDictRoute
  '/manage/log': typeof ManageLogRoute
  '/manage/task': typeof ManageTaskRoute
  '/monitoring/checks': typeof MonitoringChecksRoute
  '/monitoring/nodes': typeof MonitoringNodesRoute
  '/monitoring/overview': typeof MonitoringOverviewRoute
  '/reports/runs': typeof ReportsRunsRoute
  '/reports/templates': typeof ReportsTemplatesRoute
  '/system/menu': typeof SystemMenuRoute
  '/system/module': typeof SystemModuleRoute
  '/system/role': typeof SystemRoleRoute
  '/system/status': typeof SystemStatusRoute
  '/system/user': typeof SystemUserRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/403'
    | '/404'
    | '/analytics'
    | '/login'
    | '/monitoring'
    | '/profile'
    | '/reports'
    | '/analytics/details'
    | '/analytics/overview'
    | '/manage/deploy'
    | '/manage/dict'
    | '/manage/log'
    | '/manage/task'
    | '/monitoring/checks'
    | '/monitoring/nodes'
    | '/monitoring/overview'
    | '/reports/runs'
    | '/reports/templates'
    | '/system/menu'
    | '/system/module'
    | '/system/role'
    | '/system/status'
    | '/system/user'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/403'
    | '/404'
    | '/analytics'
    | '/login'
    | '/monitoring'
    | '/profile'
    | '/reports'
    | '/analytics/details'
    | '/analytics/overview'
    | '/manage/deploy'
    | '/manage/dict'
    | '/manage/log'
    | '/manage/task'
    | '/monitoring/checks'
    | '/monitoring/nodes'
    | '/monitoring/overview'
    | '/reports/runs'
    | '/reports/templates'
    | '/system/menu'
    | '/system/module'
    | '/system/role'
    | '/system/status'
    | '/system/user'
  id:
    | '__root__'
    | '/'
    | '/403'
    | '/404'
    | '/analytics'
    | '/login'
    | '/monitoring'
    | '/profile'
    | '/reports'
    | '/analytics/details'
    | '/analytics/overview'
    | '/manage/deploy'
    | '/manage/dict'
    | '/manage/log'
    | '/manage/task'
    | '/monitoring/checks'
    | '/monitoring/nodes'
    | '/monitoring/overview'
    | '/reports/runs'
    | '/reports/templates'
    | '/system/menu'
    | '/system/module'
    | '/system/role'
    | '/system/status'
    | '/system/user'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R403Route: typeof R403Route
  R404Route: typeof R404Route
  AnalyticsRoute: typeof AnalyticsRouteWithChildren
  LoginRoute: typeof LoginRoute
  MonitoringRoute: typeof MonitoringRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  ReportsRoute: typeof ReportsRouteWithChildren
  ManageDeployRoute: typeof ManageDeployRoute
  ManageDictRoute: typeof ManageDictRoute
  ManageLogRoute: typeof ManageLogRoute
  ManageTaskRoute: typeof ManageTaskRoute
  SystemMenuRoute: typeof SystemMenuRoute
  SystemModuleRoute: typeof SystemModuleRoute
  SystemRoleRoute: typeof SystemRoleRoute
  SystemStatusRoute: typeof SystemStatusRoute
  SystemUserRoute: typeof SystemUserRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/user': {
      id: '/system/user'
      path: '/system/user'
      fullPath: '/system/user'
      preLoaderRoute: typeof SystemUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/status': {
      id: '/system/status'
      path: '/system/status'
      fullPath: '/system/status'
      preLoaderRoute: typeof SystemStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/role': {
      id: '/system/role'
      path: '/system/role'
      fullPath: '/system/role'
      preLoaderRoute: typeof SystemRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/module': {
      id: '/system/module'
      path: '/system/module'
      fullPath: '/system/module'
      preLoaderRoute: typeof SystemModuleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/menu': {
      id: '/system/menu'
      path: '/system/menu'
      fullPath: '/system/menu'
      preLoaderRoute: typeof SystemMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/templates': {
      id: '/reports/templates'
      path: '/templates'
      fullPath: '/reports/templates'
      preLoaderRoute: typeof ReportsTemplatesRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/runs': {
      id: '/reports/runs'
      path: '/runs'
      fullPath: '/reports/runs'
      preLoaderRoute: typeof ReportsRunsRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/monitoring/overview': {
      id: '/monitoring/overview'
      path: '/overview'
      fullPath: '/monitoring/overview'
      preLoaderRoute: typeof MonitoringOverviewRouteImport
      parentRoute: typeof MonitoringRoute
    }
    '/monitoring/nodes': {
      id: '/monitoring/nodes'
      path: '/nodes'
      fullPath: '/monitoring/nodes'
      preLoaderRoute: typeof MonitoringNodesRouteImport
      parentRoute: typeof MonitoringRoute
    }
    '/monitoring/checks': {
      id: '/monitoring/checks'
      path: '/checks'
      fullPath: '/monitoring/checks'
      preLoaderRoute: typeof MonitoringChecksRouteImport
      parentRoute: typeof MonitoringRoute
    }
    '/manage/task': {
      id: '/manage/task'
      path: '/manage/task'
      fullPath: '/manage/task'
      preLoaderRoute: typeof ManageTaskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/log': {
      id: '/manage/log'
      path: '/manage/log'
      fullPath: '/manage/log'
      preLoaderRoute: typeof ManageLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/dict': {
      id: '/manage/dict'
      path: '/manage/dict'
      fullPath: '/manage/dict'
      preLoaderRoute: typeof ManageDictRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/deploy': {
      id: '/manage/deploy'
      path: '/manage/deploy'
      fullPath: '/manage/deploy'
      preLoaderRoute: typeof ManageDeployRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/overview': {
      id: '/analytics/overview'
      path: '/overview'
      fullPath: '/analytics/overview'
      preLoaderRoute: typeof AnalyticsOverviewRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/details': {
      id: '/analytics/details'
      path: '/details'
      fullPath: '/analytics/details'
      preLoaderRoute: typeof AnalyticsDetailsRouteImport
      parentRoute: typeof AnalyticsRoute
    }
  }
}

interface AnalyticsRouteChildren {
  AnalyticsDetailsRoute: typeof AnalyticsDetailsRoute
  AnalyticsOverviewRoute: typeof AnalyticsOverviewRoute
}

const AnalyticsRouteChildren: AnalyticsRouteChildren = {
  AnalyticsDetailsRoute: AnalyticsDetailsRoute,
  AnalyticsOverviewRoute: AnalyticsOverviewRoute,
}

const AnalyticsRouteWithChildren = AnalyticsRoute._addFileChildren(
  AnalyticsRouteChildren,
)

interface MonitoringRouteChildren {
  MonitoringChecksRoute: typeof MonitoringChecksRoute
  MonitoringNodesRoute: typeof MonitoringNodesRoute
  MonitoringOverviewRoute: typeof MonitoringOverviewRoute
}

const MonitoringRouteChildren: MonitoringRouteChildren = {
  MonitoringChecksRoute: MonitoringChecksRoute,
  MonitoringNodesRoute: MonitoringNodesRoute,
  MonitoringOverviewRoute: MonitoringOverviewRoute,
}

const MonitoringRouteWithChildren = MonitoringRoute._addFileChildren(
  MonitoringRouteChildren,
)

interface ReportsRouteChildren {
  ReportsRunsRoute: typeof ReportsRunsRoute
  ReportsTemplatesRoute: typeof ReportsTemplatesRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsRunsRoute: ReportsRunsRoute,
  ReportsTemplatesRoute: ReportsTemplatesRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R403Route: R403Route,
  R404Route: R404Route,
  AnalyticsRoute: AnalyticsRouteWithChildren,
  LoginRoute: LoginRoute,
  MonitoringRoute: MonitoringRouteWithChildren,
  ProfileRoute: ProfileRoute,
  ReportsRoute: ReportsRouteWithChildren,
  ManageDeployRoute: ManageDeployRoute,
  ManageDictRoute: ManageDictRoute,
  ManageLogRoute: ManageLogRoute,
  ManageTaskRoute: ManageTaskRoute,
  SystemMenuRoute: SystemMenuRoute,
  SystemModuleRoute: SystemModuleRoute,
  SystemRoleRoute: SystemRoleRoute,
  SystemStatusRoute: SystemStatusRoute,
  SystemUserRoute: SystemUserRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
