/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MonitoringRouteImport } from './routes/monitoring'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AutomationRouteImport } from './routes/automation'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as R404RouteImport } from './routes/404'
import { Route as R403RouteImport } from './routes/403'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SystemUserRouteImport } from './routes/system/user'
import { Route as SystemStatusRouteImport } from './routes/system/status'
import { Route as SystemRoleRouteImport } from './routes/system/role'
import { Route as SystemModuleRouteImport } from './routes/system/module'
import { Route as SystemMenuRouteImport } from './routes/system/menu'
import { Route as MonitoringSettingsRouteImport } from './routes/monitoring/settings'
import { Route as MonitoringOverviewRouteImport } from './routes/monitoring/overview'
import { Route as MonitoringNodesRouteImport } from './routes/monitoring/nodes'
import { Route as MonitoringIncidentsRouteImport } from './routes/monitoring/incidents'
import { Route as MonitoringChecksRouteImport } from './routes/monitoring/checks'
import { Route as ManageTaskRouteImport } from './routes/manage/task'
import { Route as ManageLogRouteImport } from './routes/manage/log'
import { Route as ManageDictRouteImport } from './routes/manage/dict'
import { Route as ManageDeployRouteImport } from './routes/manage/deploy'
import { Route as AutomationSystemsRouteImport } from './routes/automation/systems'
import { Route as AutomationSettingsRouteImport } from './routes/automation/settings'
import { Route as AutomationSchedulesRouteImport } from './routes/automation/schedules'
import { Route as AutomationRunsRouteImport } from './routes/automation/runs'
import { Route as AutomationFlowsRouteImport } from './routes/automation/flows'
import { Route as AnalyticsUsersRouteImport } from './routes/analytics/users'
import { Route as AnalyticsSettingsRouteImport } from './routes/analytics/settings'
import { Route as AnalyticsProjectsRouteImport } from './routes/analytics/projects'
import { Route as AnalyticsPagesRouteImport } from './routes/analytics/pages'
import { Route as AnalyticsOverviewRouteImport } from './routes/analytics/overview'
import { Route as AnalyticsEventsRouteImport } from './routes/analytics/events'
import { Route as AnalyticsApisRouteImport } from './routes/analytics/apis'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationRoute = AutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemUserRoute = SystemUserRouteImport.update({
  id: '/system/user',
  path: '/system/user',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemStatusRoute = SystemStatusRouteImport.update({
  id: '/system/status',
  path: '/system/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoleRoute = SystemRoleRouteImport.update({
  id: '/system/role',
  path: '/system/role',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemModuleRoute = SystemModuleRouteImport.update({
  id: '/system/module',
  path: '/system/module',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemMenuRoute = SystemMenuRouteImport.update({
  id: '/system/menu',
  path: '/system/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringSettingsRoute = MonitoringSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MonitoringRoute,
} as any)
const MonitoringOverviewRoute = MonitoringOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => MonitoringRoute,
} as any)
const MonitoringNodesRoute = MonitoringNodesRouteImport.update({
  id: '/nodes',
  path: '/nodes',
  getParentRoute: () => MonitoringRoute,
} as any)
const MonitoringIncidentsRoute = MonitoringIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => MonitoringRoute,
} as any)
const MonitoringChecksRoute = MonitoringChecksRouteImport.update({
  id: '/checks',
  path: '/checks',
  getParentRoute: () => MonitoringRoute,
} as any)
const ManageTaskRoute = ManageTaskRouteImport.update({
  id: '/manage/task',
  path: '/manage/task',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageLogRoute = ManageLogRouteImport.update({
  id: '/manage/log',
  path: '/manage/log',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageDictRoute = ManageDictRouteImport.update({
  id: '/manage/dict',
  path: '/manage/dict',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageDeployRoute = ManageDeployRouteImport.update({
  id: '/manage/deploy',
  path: '/manage/deploy',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationSystemsRoute = AutomationSystemsRouteImport.update({
  id: '/systems',
  path: '/systems',
  getParentRoute: () => AutomationRoute,
} as any)
const AutomationSettingsRoute = AutomationSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AutomationRoute,
} as any)
const AutomationSchedulesRoute = AutomationSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => AutomationRoute,
} as any)
const AutomationRunsRoute = AutomationRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => AutomationRoute,
} as any)
const AutomationFlowsRoute = AutomationFlowsRouteImport.update({
  id: '/flows',
  path: '/flows',
  getParentRoute: () => AutomationRoute,
} as any)
const AnalyticsUsersRoute = AnalyticsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsSettingsRoute = AnalyticsSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsProjectsRoute = AnalyticsProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsPagesRoute = AnalyticsPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsOverviewRoute = AnalyticsOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsEventsRoute = AnalyticsEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsApisRoute = AnalyticsApisRouteImport.update({
  id: '/apis',
  path: '/apis',
  getParentRoute: () => AnalyticsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/404': typeof R404Route
  '/analytics': typeof AnalyticsRouteWithChildren
  '/automation': typeof AutomationRouteWithChildren
  '/login': typeof LoginRoute
  '/monitoring': typeof MonitoringRouteWithChildren
  '/profile': typeof ProfileRoute
  '/analytics/apis': typeof AnalyticsApisRoute
  '/analytics/events': typeof AnalyticsEventsRoute
  '/analytics/overview': typeof AnalyticsOverviewRoute
  '/analytics/pages': typeof AnalyticsPagesRoute
  '/analytics/projects': typeof AnalyticsProjectsRoute
  '/analytics/settings': typeof AnalyticsSettingsRoute
  '/analytics/users': typeof AnalyticsUsersRoute
  '/automation/flows': typeof AutomationFlowsRoute
  '/automation/runs': typeof AutomationRunsRoute
  '/automation/schedules': typeof AutomationSchedulesRoute
  '/automation/settings': typeof AutomationSettingsRoute
  '/automation/systems': typeof AutomationSystemsRoute
  '/manage/deploy': typeof ManageDeployRoute
  '/manage/dict': typeof ManageDictRoute
  '/manage/log': typeof ManageLogRoute
  '/manage/task': typeof ManageTaskRoute
  '/monitoring/checks': typeof MonitoringChecksRoute
  '/monitoring/incidents': typeof MonitoringIncidentsRoute
  '/monitoring/nodes': typeof MonitoringNodesRoute
  '/monitoring/overview': typeof MonitoringOverviewRoute
  '/monitoring/settings': typeof MonitoringSettingsRoute
  '/system/menu': typeof SystemMenuRoute
  '/system/module': typeof SystemModuleRoute
  '/system/role': typeof SystemRoleRoute
  '/system/status': typeof SystemStatusRoute
  '/system/user': typeof SystemUserRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/404': typeof R404Route
  '/analytics': typeof AnalyticsRouteWithChildren
  '/automation': typeof AutomationRouteWithChildren
  '/login': typeof LoginRoute
  '/monitoring': typeof MonitoringRouteWithChildren
  '/profile': typeof ProfileRoute
  '/analytics/apis': typeof AnalyticsApisRoute
  '/analytics/events': typeof AnalyticsEventsRoute
  '/analytics/overview': typeof AnalyticsOverviewRoute
  '/analytics/pages': typeof AnalyticsPagesRoute
  '/analytics/projects': typeof AnalyticsProjectsRoute
  '/analytics/settings': typeof AnalyticsSettingsRoute
  '/analytics/users': typeof AnalyticsUsersRoute
  '/automation/flows': typeof AutomationFlowsRoute
  '/automation/runs': typeof AutomationRunsRoute
  '/automation/schedules': typeof AutomationSchedulesRoute
  '/automation/settings': typeof AutomationSettingsRoute
  '/automation/systems': typeof AutomationSystemsRoute
  '/manage/deploy': typeof ManageDeployRoute
  '/manage/dict': typeof ManageDictRoute
  '/manage/log': typeof ManageLogRoute
  '/manage/task': typeof ManageTaskRoute
  '/monitoring/checks': typeof MonitoringChecksRoute
  '/monitoring/incidents': typeof MonitoringIncidentsRoute
  '/monitoring/nodes': typeof MonitoringNodesRoute
  '/monitoring/overview': typeof MonitoringOverviewRoute
  '/monitoring/settings': typeof MonitoringSettingsRoute
  '/system/menu': typeof SystemMenuRoute
  '/system/module': typeof SystemModuleRoute
  '/system/role': typeof SystemRoleRoute
  '/system/status': typeof SystemStatusRoute
  '/system/user': typeof SystemUserRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/404': typeof R404Route
  '/analytics': typeof AnalyticsRouteWithChildren
  '/automation': typeof AutomationRouteWithChildren
  '/login': typeof LoginRoute
  '/monitoring': typeof MonitoringRouteWithChildren
  '/profile': typeof ProfileRoute
  '/analytics/apis': typeof AnalyticsApisRoute
  '/analytics/events': typeof AnalyticsEventsRoute
  '/analytics/overview': typeof AnalyticsOverviewRoute
  '/analytics/pages': typeof AnalyticsPagesRoute
  '/analytics/projects': typeof AnalyticsProjectsRoute
  '/analytics/settings': typeof AnalyticsSettingsRoute
  '/analytics/users': typeof AnalyticsUsersRoute
  '/automation/flows': typeof AutomationFlowsRoute
  '/automation/runs': typeof AutomationRunsRoute
  '/automation/schedules': typeof AutomationSchedulesRoute
  '/automation/settings': typeof AutomationSettingsRoute
  '/automation/systems': typeof AutomationSystemsRoute
  '/manage/deploy': typeof ManageDeployRoute
  '/manage/dict': typeof ManageDictRoute
  '/manage/log': typeof ManageLogRoute
  '/manage/task': typeof ManageTaskRoute
  '/monitoring/checks': typeof MonitoringChecksRoute
  '/monitoring/incidents': typeof MonitoringIncidentsRoute
  '/monitoring/nodes': typeof MonitoringNodesRoute
  '/monitoring/overview': typeof MonitoringOverviewRoute
  '/monitoring/settings': typeof MonitoringSettingsRoute
  '/system/menu': typeof SystemMenuRoute
  '/system/module': typeof SystemModuleRoute
  '/system/role': typeof SystemRoleRoute
  '/system/status': typeof SystemStatusRoute
  '/system/user': typeof SystemUserRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/403'
    | '/404'
    | '/analytics'
    | '/automation'
    | '/login'
    | '/monitoring'
    | '/profile'
    | '/analytics/apis'
    | '/analytics/events'
    | '/analytics/overview'
    | '/analytics/pages'
    | '/analytics/projects'
    | '/analytics/settings'
    | '/analytics/users'
    | '/automation/flows'
    | '/automation/runs'
    | '/automation/schedules'
    | '/automation/settings'
    | '/automation/systems'
    | '/manage/deploy'
    | '/manage/dict'
    | '/manage/log'
    | '/manage/task'
    | '/monitoring/checks'
    | '/monitoring/incidents'
    | '/monitoring/nodes'
    | '/monitoring/overview'
    | '/monitoring/settings'
    | '/system/menu'
    | '/system/module'
    | '/system/role'
    | '/system/status'
    | '/system/user'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/403'
    | '/404'
    | '/analytics'
    | '/automation'
    | '/login'
    | '/monitoring'
    | '/profile'
    | '/analytics/apis'
    | '/analytics/events'
    | '/analytics/overview'
    | '/analytics/pages'
    | '/analytics/projects'
    | '/analytics/settings'
    | '/analytics/users'
    | '/automation/flows'
    | '/automation/runs'
    | '/automation/schedules'
    | '/automation/settings'
    | '/automation/systems'
    | '/manage/deploy'
    | '/manage/dict'
    | '/manage/log'
    | '/manage/task'
    | '/monitoring/checks'
    | '/monitoring/incidents'
    | '/monitoring/nodes'
    | '/monitoring/overview'
    | '/monitoring/settings'
    | '/system/menu'
    | '/system/module'
    | '/system/role'
    | '/system/status'
    | '/system/user'
  id:
    | '__root__'
    | '/'
    | '/403'
    | '/404'
    | '/analytics'
    | '/automation'
    | '/login'
    | '/monitoring'
    | '/profile'
    | '/analytics/apis'
    | '/analytics/events'
    | '/analytics/overview'
    | '/analytics/pages'
    | '/analytics/projects'
    | '/analytics/settings'
    | '/analytics/users'
    | '/automation/flows'
    | '/automation/runs'
    | '/automation/schedules'
    | '/automation/settings'
    | '/automation/systems'
    | '/manage/deploy'
    | '/manage/dict'
    | '/manage/log'
    | '/manage/task'
    | '/monitoring/checks'
    | '/monitoring/incidents'
    | '/monitoring/nodes'
    | '/monitoring/overview'
    | '/monitoring/settings'
    | '/system/menu'
    | '/system/module'
    | '/system/role'
    | '/system/status'
    | '/system/user'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R403Route: typeof R403Route
  R404Route: typeof R404Route
  AnalyticsRoute: typeof AnalyticsRouteWithChildren
  AutomationRoute: typeof AutomationRouteWithChildren
  LoginRoute: typeof LoginRoute
  MonitoringRoute: typeof MonitoringRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  ManageDeployRoute: typeof ManageDeployRoute
  ManageDictRoute: typeof ManageDictRoute
  ManageLogRoute: typeof ManageLogRoute
  ManageTaskRoute: typeof ManageTaskRoute
  SystemMenuRoute: typeof SystemMenuRoute
  SystemModuleRoute: typeof SystemModuleRoute
  SystemRoleRoute: typeof SystemRoleRoute
  SystemStatusRoute: typeof SystemStatusRoute
  SystemUserRoute: typeof SystemUserRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation': {
      id: '/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/user': {
      id: '/system/user'
      path: '/system/user'
      fullPath: '/system/user'
      preLoaderRoute: typeof SystemUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/status': {
      id: '/system/status'
      path: '/system/status'
      fullPath: '/system/status'
      preLoaderRoute: typeof SystemStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/role': {
      id: '/system/role'
      path: '/system/role'
      fullPath: '/system/role'
      preLoaderRoute: typeof SystemRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/module': {
      id: '/system/module'
      path: '/system/module'
      fullPath: '/system/module'
      preLoaderRoute: typeof SystemModuleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/menu': {
      id: '/system/menu'
      path: '/system/menu'
      fullPath: '/system/menu'
      preLoaderRoute: typeof SystemMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring/settings': {
      id: '/monitoring/settings'
      path: '/settings'
      fullPath: '/monitoring/settings'
      preLoaderRoute: typeof MonitoringSettingsRouteImport
      parentRoute: typeof MonitoringRoute
    }
    '/monitoring/overview': {
      id: '/monitoring/overview'
      path: '/overview'
      fullPath: '/monitoring/overview'
      preLoaderRoute: typeof MonitoringOverviewRouteImport
      parentRoute: typeof MonitoringRoute
    }
    '/monitoring/nodes': {
      id: '/monitoring/nodes'
      path: '/nodes'
      fullPath: '/monitoring/nodes'
      preLoaderRoute: typeof MonitoringNodesRouteImport
      parentRoute: typeof MonitoringRoute
    }
    '/monitoring/incidents': {
      id: '/monitoring/incidents'
      path: '/incidents'
      fullPath: '/monitoring/incidents'
      preLoaderRoute: typeof MonitoringIncidentsRouteImport
      parentRoute: typeof MonitoringRoute
    }
    '/monitoring/checks': {
      id: '/monitoring/checks'
      path: '/checks'
      fullPath: '/monitoring/checks'
      preLoaderRoute: typeof MonitoringChecksRouteImport
      parentRoute: typeof MonitoringRoute
    }
    '/manage/task': {
      id: '/manage/task'
      path: '/manage/task'
      fullPath: '/manage/task'
      preLoaderRoute: typeof ManageTaskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/log': {
      id: '/manage/log'
      path: '/manage/log'
      fullPath: '/manage/log'
      preLoaderRoute: typeof ManageLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/dict': {
      id: '/manage/dict'
      path: '/manage/dict'
      fullPath: '/manage/dict'
      preLoaderRoute: typeof ManageDictRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/deploy': {
      id: '/manage/deploy'
      path: '/manage/deploy'
      fullPath: '/manage/deploy'
      preLoaderRoute: typeof ManageDeployRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation/systems': {
      id: '/automation/systems'
      path: '/systems'
      fullPath: '/automation/systems'
      preLoaderRoute: typeof AutomationSystemsRouteImport
      parentRoute: typeof AutomationRoute
    }
    '/automation/settings': {
      id: '/automation/settings'
      path: '/settings'
      fullPath: '/automation/settings'
      preLoaderRoute: typeof AutomationSettingsRouteImport
      parentRoute: typeof AutomationRoute
    }
    '/automation/schedules': {
      id: '/automation/schedules'
      path: '/schedules'
      fullPath: '/automation/schedules'
      preLoaderRoute: typeof AutomationSchedulesRouteImport
      parentRoute: typeof AutomationRoute
    }
    '/automation/runs': {
      id: '/automation/runs'
      path: '/runs'
      fullPath: '/automation/runs'
      preLoaderRoute: typeof AutomationRunsRouteImport
      parentRoute: typeof AutomationRoute
    }
    '/automation/flows': {
      id: '/automation/flows'
      path: '/flows'
      fullPath: '/automation/flows'
      preLoaderRoute: typeof AutomationFlowsRouteImport
      parentRoute: typeof AutomationRoute
    }
    '/analytics/users': {
      id: '/analytics/users'
      path: '/users'
      fullPath: '/analytics/users'
      preLoaderRoute: typeof AnalyticsUsersRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/settings': {
      id: '/analytics/settings'
      path: '/settings'
      fullPath: '/analytics/settings'
      preLoaderRoute: typeof AnalyticsSettingsRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/projects': {
      id: '/analytics/projects'
      path: '/projects'
      fullPath: '/analytics/projects'
      preLoaderRoute: typeof AnalyticsProjectsRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/pages': {
      id: '/analytics/pages'
      path: '/pages'
      fullPath: '/analytics/pages'
      preLoaderRoute: typeof AnalyticsPagesRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/overview': {
      id: '/analytics/overview'
      path: '/overview'
      fullPath: '/analytics/overview'
      preLoaderRoute: typeof AnalyticsOverviewRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/events': {
      id: '/analytics/events'
      path: '/events'
      fullPath: '/analytics/events'
      preLoaderRoute: typeof AnalyticsEventsRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/apis': {
      id: '/analytics/apis'
      path: '/apis'
      fullPath: '/analytics/apis'
      preLoaderRoute: typeof AnalyticsApisRouteImport
      parentRoute: typeof AnalyticsRoute
    }
  }
}

interface AnalyticsRouteChildren {
  AnalyticsApisRoute: typeof AnalyticsApisRoute
  AnalyticsEventsRoute: typeof AnalyticsEventsRoute
  AnalyticsOverviewRoute: typeof AnalyticsOverviewRoute
  AnalyticsPagesRoute: typeof AnalyticsPagesRoute
  AnalyticsProjectsRoute: typeof AnalyticsProjectsRoute
  AnalyticsSettingsRoute: typeof AnalyticsSettingsRoute
  AnalyticsUsersRoute: typeof AnalyticsUsersRoute
}

const AnalyticsRouteChildren: AnalyticsRouteChildren = {
  AnalyticsApisRoute: AnalyticsApisRoute,
  AnalyticsEventsRoute: AnalyticsEventsRoute,
  AnalyticsOverviewRoute: AnalyticsOverviewRoute,
  AnalyticsPagesRoute: AnalyticsPagesRoute,
  AnalyticsProjectsRoute: AnalyticsProjectsRoute,
  AnalyticsSettingsRoute: AnalyticsSettingsRoute,
  AnalyticsUsersRoute: AnalyticsUsersRoute,
}

const AnalyticsRouteWithChildren = AnalyticsRoute._addFileChildren(
  AnalyticsRouteChildren,
)

interface AutomationRouteChildren {
  AutomationFlowsRoute: typeof AutomationFlowsRoute
  AutomationRunsRoute: typeof AutomationRunsRoute
  AutomationSchedulesRoute: typeof AutomationSchedulesRoute
  AutomationSettingsRoute: typeof AutomationSettingsRoute
  AutomationSystemsRoute: typeof AutomationSystemsRoute
}

const AutomationRouteChildren: AutomationRouteChildren = {
  AutomationFlowsRoute: AutomationFlowsRoute,
  AutomationRunsRoute: AutomationRunsRoute,
  AutomationSchedulesRoute: AutomationSchedulesRoute,
  AutomationSettingsRoute: AutomationSettingsRoute,
  AutomationSystemsRoute: AutomationSystemsRoute,
}

const AutomationRouteWithChildren = AutomationRoute._addFileChildren(
  AutomationRouteChildren,
)

interface MonitoringRouteChildren {
  MonitoringChecksRoute: typeof MonitoringChecksRoute
  MonitoringIncidentsRoute: typeof MonitoringIncidentsRoute
  MonitoringNodesRoute: typeof MonitoringNodesRoute
  MonitoringOverviewRoute: typeof MonitoringOverviewRoute
  MonitoringSettingsRoute: typeof MonitoringSettingsRoute
}

const MonitoringRouteChildren: MonitoringRouteChildren = {
  MonitoringChecksRoute: MonitoringChecksRoute,
  MonitoringIncidentsRoute: MonitoringIncidentsRoute,
  MonitoringNodesRoute: MonitoringNodesRoute,
  MonitoringOverviewRoute: MonitoringOverviewRoute,
  MonitoringSettingsRoute: MonitoringSettingsRoute,
}

const MonitoringRouteWithChildren = MonitoringRoute._addFileChildren(
  MonitoringRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R403Route: R403Route,
  R404Route: R404Route,
  AnalyticsRoute: AnalyticsRouteWithChildren,
  AutomationRoute: AutomationRouteWithChildren,
  LoginRoute: LoginRoute,
  MonitoringRoute: MonitoringRouteWithChildren,
  ProfileRoute: ProfileRoute,
  ManageDeployRoute: ManageDeployRoute,
  ManageDictRoute: ManageDictRoute,
  ManageLogRoute: ManageLogRoute,
  ManageTaskRoute: ManageTaskRoute,
  SystemMenuRoute: SystemMenuRoute,
  SystemModuleRoute: SystemModuleRoute,
  SystemRoleRoute: SystemRoleRoute,
  SystemStatusRoute: SystemStatusRoute,
  SystemUserRoute: SystemUserRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
