name: Backend Build

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Build binary
              run: docker buildx build --platform linux/amd64 --target binary --output type=local,dest=target/dist/bin -f deploy/binary.Dockerfile .

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: rustzen-admin-binary
                  path: target/dist/bin/rustzen-admin
                  retention-days: 30
