name: Frontend Build

on:
    workflow_dispatch:

env:
    NODE_VERSION: "24.2.0"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Setup Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: pnpm
                  cache-dependency-path: apps/web/pnpm-lock.yaml

            - name: Enable pnpm
              run: |
                  corepack enable
                  corepack prepare pnpm@11.2.2 --activate

            - name: Install dependencies
              run: pnpm install --frozen-lockfile
              working-directory: apps/web

            - name: Build frontend
              run: pnpm build
              working-directory: apps/web

            - name: Collect artifact
              run: |
                  VERSION=$(awk -F '"' '/^version = / { print $2; exit }' apps/server/Cargo.toml)
                  mkdir -p target/rustzen-admin
                  mv apps/web/dist-rustzen-admin-*.zip target/rustzen-admin/dist-$VERSION.zip

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: frontend-dist
                  path: target/rustzen-admin/dist-*.zip
                  retention-days: 30
