name: Full Stack Build

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Build release package
              run: docker buildx build --platform linux/amd64 --target release --output type=local,dest=target/dist -f deploy/release.Dockerfile .

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: rustzen-admin-release
                  path: target/dist/rustzen-admin.zip
